### ISSUE TITLE
DateRangePicker blinking after select startDate

### ISSUE THREAD

**Issue by thais-molica** [airbnb/react-dates#1523]
Hello, there.
I'm  setting up DateRangePicker, but when I select startDate the calendar blinks. 

![screencast-localhost-3000-2019 02 01-11-33-13](https://user-images.githubusercontent.com/9726793/52126556-c6ebf800-2616-11e9-9a7b-4c443e1fdb53.gif)

Here's my code

```
<DateRangePicker
        startDate={this.state.startDate} 
        startDateId="startDate" 
        endDate={this.state.endDate} 
        endDateId="endDate" 
        onDatesChange={({ startDate, endDate }) => this.setState({startDate, endDate})}
        focusedInput={this.state.focusedInput}
        onFocusChange={focusedInput => this.setState({focusedInput})} 
      />
```

**Comment by fillipe-ramos** [comment]
I have the same issue

**Comment by avaldelvira** [comment]
I'm having the same issue, anybody knows something about this issue? 

Thanks @fillipe-ramos for the tip, that version works perfectly for me.

**Comment by danedavid** [comment]
I'm looking into this.

**Comment by GfxKai** [comment]
In case it helps track down the cause of this issue: if you select a start date that isn't within the leftmost month, the calendar re-renders to show that month on the far left. This doesn't happen pre-18.3.1.

![ohdear](https://user-images.githubusercontent.com/22200114/52965665-47438480-339d-11e9-84fb-0959d47d421f.gif)

**Comment by GfxKai** [comment]
Looks like this is something to do with the change of focus between the start date and end date inputs, which happens to be triggered when you select a date. If you simply select the end date input box directly, the same flashing occurs. This doesn't happen in 18.4.0.

**Comment by mmakarin** [comment]
Still flickering for me in 18.4.1

**Comment by sergiubologa** [comment]
There's an open PR for this: https://github.com/airbnb/react-dates/pull/1553

**Comment by mmakarin** [comment]
Any updates? It's failing on line max length check.

**Comment by GfxKai** [comment]
@mmakarin over by 1 character 🤦‍♂️ just fixed in a new commit, should be fine now!

**Comment by viros** [comment]
Any updates?

**Comment by sergiubologa** [comment]
Check out htis PR: https://github.com/airbnb/react-dates/pull/1553

**Comment by dmitryrn** [comment]
Still blinking on 20.2.5

**Comment by EugeneDraitsev** [comment]
@GfxKai Why this issue still tagged as `pull request wanted` and why #1553 is still doesn't merged?

**Comment by ljharb** [comment]
@EugeneDraitsev please do not open duplicate PRs; it’s unnecessary (maintainers can update abandoned PRs directly) and it adds permanent garbage to the git log.

**Comment by EugeneDraitsev** [comment]
@ljharb Ok, I closed my PR. Will try to help with tests for `SingleDatePickerInput.jsx` and comment #1553 with link to changes

**Comment by mthahzan** [comment]
This is merged but doesn't seem to be released yet. Any updates on when this will be released?
